stages:
  - deploy

variables:
  CI: "false"

deploy-job-test:
  image: alpine:3.8
  stage: deploy
  only:
    - test
  before_script:
    - apk add --update -t deps curl
  script:
    - ls -lht
    - >-
      curl -k --location --request POST 'https://ft-project-deployer-prod.run.fish/deploy'
      --header 'token:'$CICD_TOKEN
      --form 'project=@"'$CI_PROJECT_DIR'/dist.zip"'
      --form 'version="'$CI_COMMIT_SHORT_SHA'"'
      --form 'envs="x=x"'
  environment:
    name: test


deploy-job-prod:
  image: alpine:3.8
  stage: deploy
  only:
    - prod
  before_script:
    - apk add --update -t deps curl
    - curl -L http://gosspublic.alicdn.com/ossutil/1.7.8/ossutil64 -o /usr/local/bin/ossutil64
    - chmod +x /usr/local/bin/ossutil64
  script:
    - ossutil64 sync $BUILD_DIR oss://$BUCKET/ -f --delete -e $ENDPOINT -i $ACCESS_KEY_ID -k $ACCESS_KEY_SECRET
  environment:
    name: prod
